### ISSUE TITLE
문서를 docx에서 md(마크다운) 문서로 변환

### ISSUE THREAD

**Issue by jacking75** [blackwitch/Coconut#1]
현재 문서가 MS Word 문서로 되어 있어서 문서를 보려면 따로 문서를 다운로드 해야 하고 컴퓨터에 MS Word가 설치 되어야 합니다.
지금 보다 더 쉽게 문서를 보고 수정하기 위해서 문서를 md(문법은 github에 맞추어) 포맷으로 변환하면 어떨까 합니다.
참고로 md로 관리하면 github에서 바로 수정도 가능합니다

혹시 작업할 시간이 부족하다면 제가 1챕터씩 작업해 보겠습니다^^

**Comment by blackwitch** [comment]
좋은 의견 감사합니다.

저는 다른 업데이트가 마무리되면 모든 메뉴얼을 gitbook으로 변경을 할까 고민중입니다.

md는 제가 한번도 해본적이 없지만, 쉽게 볼 수 있다면 변환하는 쪽이 더 좋다고 생각됩니다. (혹시 gitbook에서도 활용되는 포멧인가요??)

오픈소스를 관리하는 것도 처음이라 염치 불고하고 부탁을 드립니다.

github는 이번이 처음이라 필요한 사항이 있으면 메일로 보내주시고, 급하게 필요한 사항이 있다면 카톡으로 보내주시면 바로 지원해 드리겠습니다. 

감사합니다. ^^

**Comment by jacking75** [comment]
gitbook을 보니 md로 만들 문서를 사용하는 것이군요^^
그럼 별문제 없으면 지금 github에 올라온 워드문서를 제가 md 문서로 만들어 보겠습니다.
내용이 많지 않아서 그리 시간은 많이 걸리지 않을 것 같네요

md가 일종의 위키와 비슷해서 워드 사용보다는 좀 불편합니다. 게다가 문법도 조금씩 다르더군요(위키처럼)^^;
그래도 확장성이 좋아서 화려한 문서가 아니라면 md로 하는 것이 좋습니다.
늦어도 다음 주말까지는 1차 변환해서 보내 드리겠습니다^^

2015년 4월 24일 오전 10:53, JiHyun, LEE notifications@github.com님이 작성:

> 좋은 의견 감사합니다.
> 
> 저는 다른 업데이트가 마무리되면 모든 메뉴얼을 gitbook으로 변경을 할까 고민중입니다.
> 
> md는 제가 한번도 해본적이 없어서...(혹시 gitbook에서도 활용되는 포멧인가요??)
> 
> 오픈소스를 관리하는 것도 처음이라...
> 
> 염치 불고하고 부탁을 드립니다.
> 
> github는 이번이 처음이라 필요한 사항이 있으면 메일로 보내주시고, 급하게 필요한 사항이 있다면 카톡으로 보내주시면 바로 지원해
> 드리겠습니다.
> 
> 감사합니다. ^^
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/blackwitch/Coconut/issues/1#issuecomment-95772997.

## 

Twitter : @jacking75
Blog : http://jacking.tistory.com/

**Comment by blackwitch** [comment]
신경 많이 써주셔서 감사합니다. 

오픈 준비가 되는데로 나머지 부분은 제가 다시 정리 하겠습니다. ^^

**Comment by blackwitch** [comment]
이 이슈는 닫아 두겠습니다.
