### ISSUE TITLE
에이전트 서버 실행시 에러 문제

### ISSUE THREAD

**Issue by pdpdds** [blackwitch/Coconut#2]
윈도우즈 7 운영체제에서 에이전트 서버를 실행할 시 에러가 발생합니다.

에러 내용
TypeError: Cannot call method 'map' of null

node_modules/windows-cpu/index.js:139:42 부분을 지적하고 있으며
해당 코드 부분은
var cpus = res.match(/\d+/g).map(function(x) { 
부분입니다.

확인해 주시면 감사하겠습니다.

**Comment by blackwitch** [comment]
해당 모듈은 제가 만든게 아닌, 외부 모듈입니다. 테스트 결과 제 PC에서 문제가 발생하지 않는 상태입니다. 혹시 제가 pdpdds님의 가동환경을 시뮬레이션 할 수 있는 어떤 정보를 추가로 주실 수 있는지요.

**Comment by blackwitch** [comment]
사무실 PC 2대 /개인 노트북 1대 (windows 7 입니다.) 에 설치해서 테스트 해본 결과 해당 위치에서의 특별한 문제는 발생하지 않았습니다. 

설치 절차와 상세한 에러 메세지를 보내주시면 다시 한번 검토해 보겠습니다.

**Comment by pdpdds** [comment]
두세번 더 해봤었는데 똑같은 문제가 발생했었습니다. 내일 중으로 설치 절차 및 에러 메세지를 정리해서 올리겠습니다.

**Comment by jacking75** [comment]
주항님 질문과 좀 상관 없는 글이지만 저의 첫 실행 결과 알립니다^^;
저는 Windows 8.1 64비트입니다. Manager와 Agent 둘만 실행했는데 에러는 발생하지 않네요

**Comment by pdpdds** [comment]
메일로 테스트 관련 문서를 보내드렸습니다.

**Comment by blackwitch** [comment]
확인 감사합니다. 설치를 잘못 하신 내용은 없는 듯 하며, 금일 업무 PC를 업그레이드 해야 해서 오후 정도에 관련 내용에 대해서 확인  후 답변 드리겠습니다.

**Comment by jacking75** [comment]
혹시 문제 부분이 찾아지지 않느다면 MPSreports 툴을 사용해보기를 추천합니다.
MPSreports 라는 툴을 사용하면 컴퓨터의 OS나 여러 자잘한 정보를 파일로 출력해 줍니다.
이걸 지현님께 전달하면 어떤 문제인지 분석할 때 도움이 될 것 같아요^^

MPSreports
http://blogs.technet.com/b/yongrhee/archive/2013/10/16/tool-mpsreports-replacement-as-of-oct-6th-2013.aspx

http://hbkims.tistory.com/entry/MPS-Report-%EC%88%98%EC%A7%91-%EB%B0%A9%EB%B2%95-%EB%B0%8F-%ED%95%AD%EB%AA%A9%EB%B3%84-%EB%82%B4%EC%9A%A9-%EC%84%A4%EB%AA%85

**Comment by blackwitch** [comment]
단순한 파싱 문제라고 판단됩니다. 제가 원인을 확인할 수 있는 로그 코드를 추가하여 내일 파일을 드리겠습니다. 그걸 보면 원인은 쉽게 확인할 수 있을거라 생각됩니다.

**Comment by blackwitch** [comment]
문제가 된 코드를 아래와 같이 수정해 보시기 바랍니다.

wmic를 실행한 결과를 파싱할 때 잘못된 결과가 나오는 경우가 있는 듯 합니다.
혹시 totalLoad error로그가 남으면 해당 내용을 보내주시면, 해당 프로젝트에 수정을 건의하겠습니다.

```
        var check = res.match(/\d+/g);
        var cpus ='';
        if(check){
            cpus = check.map(function(x) { 
                return +(x.trim()); 
            });
        }else{
                            console.log( 'totalLoad error : ' + res );
                    }
```

**Comment by pdpdds** [comment]
수정해서 돌려보니 에이전트가 죽지 않네요. 혹시나 해서 원래 코드로 돌려서 다시 실행해 보니 그래도 죽지 않습니다. 재현에 성공하면 코드를 적용해서 로그를 보내드리겠습니다(100% 재현되다가 지금 해보니 재현이 안되네요 -.-)

**Comment by pdpdds** [comment]
그리고 이건 다른 질문인데 툴 웹페이지에 접속하면 터미널의 로긴/패스워드를 묻는데 매니저 서버에 설정해야 하는 암호인가요, 아님 에이전트 서버가 설치된 데스크탑의 로긴 아이디/패스워드를 의미하는 건지요. 입력해도 반응이 없어 문의 드립니다.

**Comment by pdpdds** [comment]
에이전트를 종료하고 자바스크립트 코드를 수정해서 저장후 다시 실행할 때 바로 스크립트가 반영되지 않은 것 같습니다. 컴퓨터 재부팅후 수정된 코드를 적용해서 실행하니 에이전트 서버가 죽지 않으며 콘솔창에 로그를 남기지는 않습니다(이전 코드로 에이전트 서버를 실행했을 때는 100% 서버가 죽는 것 확인했습니다)

**Comment by pdpdds** [comment]
다음과 같은 에러 로그를 남겼습니다.
totalLoad error : LoadPercentage
이것만 가지고 원인을 유추할 수 있을지 모르겠네요. 확인이 힘들다면 추후에 제가 디버깅 도구 설치해서 디버깅 해보도록 하겠습니다.
혹 제 컴퓨터의 cpu가 6코어인데 이게 문제가 될수도 있을 것 같다는 막연한 생각이 갑자기 듭니다;;;

**Comment by blackwitch** [comment]
확인 감사합니다. CPU 사용률 검색할 때 뒤에 사용률이 나와야 되는데 안나오는 경우가 있나 보네요. 해당 내용에 대해서는 개발자와 논의해서 반영하도록 한 후 이 이슈를 닫도록 하겠습니다. 관련해서 코멘트 다시 남겨드릴께요. ~ 

그리고 터미널의 id/pw는 ... 없습니다. ^^a

관리자에 대한 id/pw 관리가 꼭 필요할까 라는 고민을 좀 하고 있어서요. 

그에 대해서는 추후 ssh 도입하면서나 그전에 필요한 분들이 요청하면 처리할 까 생각중에 있습니다. 혹시 필요하시다면 이번에 추가를 하겠습니다.

**Comment by blackwitch** [comment]
https://github.com/KyleRoss/windows-cpu/blob/master/index.js

현재 최신 버전에서는 이 내용에 대한 처리가 이미 되어 있습니다. 

```
        var cpus = (res.match(/\d+/g) || []).map(function(x) { 
            return +(x.trim()); 
        });
```

이처럼 예외처리 되어 있어서 따로 요청할 필요가 없을 듯 하네요. npm으로 받아보니 적용되어 내려받아집니다. ^^

해당 이슈는 닫도록 하겠습니다. 

id/pw 관리에 대해서 필요하시다면 별도 이슈로 요청 부탁드립니다.

**Comment by blackwitch** [comment]
아.. 추가로 package.json 을 수정해 둬야겠네요. 바로 변경해서 적용하겠습니다. ^^
