### ISSUE TITLE
Tool과 Manager과 http API, Manger와 Agent간의 rpc API 리스트를 알려주시면 좋겠습니다^^

### ISSUE THREAD

**Issue by jacking75** [blackwitch/Coconut#4]
제가 보기에 Tool과 Manager는 http 통신으로 요청과 응답을 주고 받고,
Manager와 Agent는 웹소켓을 사용한 rpc 통신으로 요청과 응답을 주고 받는 것 같더군요.

그래서 Tool과 Manager 간의 http API를 알면 어떤 기능이 있는지 쉽게 알 수 있을 것 같습니다.
예를들면 이런식... http://blog.outsider.ne.kr/attach/1/2722581072.gif.pagespeed.ce.UL_wjckWOc.gif
그리고 api 포맷만 알면 원한다면 Manager와 통신을 할 수 있는 Tool을 따로 만들 수도 있어서 확장성이 늘어날 것 같습니다.

또한 Manager와 Agent간의 rpc API도 리스팅 되면 Manager와 Agent에서 제공하는 기능을 더 쉽게 파악할 수 있을 것 같습니다.

**Comment by blackwitch** [comment]
업무 관련 회의가 길어져, 금일 중으로 모두 정리하기가 힘들 듯 합니다. 

## 내일 오전 중에 메일로 정리해서 전달해 드리겠습니다.

관련 내용을 27일 오후 5시전까지 정리해서 이곳에 등록하겠습니다. ^^

**Comment by blackwitch** [comment]
관련 내용을 gmail로 전송했습니다. 필요한 사항 있으면 다시 보내주세요. ^^

**Comment by blackwitch** [comment]
웹에서 pull request 처리 했는데, 로컬에서 싱크를 시도하니 uncommit된 내용이라고 다시 커밋을 시도 하네요 --; 왜 이런건지 혹시 아시나요???

**Comment by jacking75** [comment]
저도 GitHub를 자세히 아는건 아니라서 잘 모르겠네요^^;;;
