### ISSUE TITLE
기본 Port 번호 변경

### ISSUE THREAD

**Issue by jacking75** [blackwitch/Coconut#6]
사소한 것일 수 있지만 건의합니다^^;
config.js를 보면 Manager와 Agent의 포트번호가 다음과 같습니다.
var ipMng = 'localhost';        //  ip address of Coconut Manager 
var portMngApi = 5070;          //  port number of Coconut Manager 
var portMngFileTransfer = 5060; //  file transfer port number of Coconut Manager
var portMngInternalHttp = 8080; //  http port number of Coconut Manager for Coconut Agent
var portMngExternalHttp = 8443; //  http port number of Coconut Manager for Tool User

var portAgentRpc = 5090;
var portAgentFileTransfer = 5080;

제 경험상 시스템 운영 엔지니어들은 보안상, 기존 포트번호화 충돌 등의 문제로 10000번대 이상의 포트번호를 사용하기를 선호합니다. 
그러니 배포될 때의 포트번호도 10000번대 이상의 번호로 정하면 좋을 것 같습니다.

또 개발 테스트를 하나의 PC에서 1차적으로 개발 테스트를 할 수 있으니 ip도 기본은 localhost로 하면 어떨까 합니다^^;

**Comment by blackwitch** [comment]
포트 번호는 조정하겠습니다. 혹시 추천하는 번호 있으시면 코멘트 부탁드립니다. 

또한 localhost로 변경해서 테스트 해보겠습니다. 이전에 어떤 문제가 있었는데 정확히 기억이 나질 않네요. 

일단 확인 후 이곳에 코멘트 남기겠습니다. ^^

**Comment by jacking75** [comment]
제 추천은 아래와 같습니다^^
http://ko.wikipedia.org/wiki/TCP/UDP%EC%9D%98_%ED%8F%AC%ED%8A%B8_%EB%AA%A9%EB%A1%9D
http://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers
에서 알려진 포트번호를 참고 했습니다

var ipMng = 'localhost'; // ip address of Coconut Manager 
var portMngApi = 38150; // port number of Coconut Manager 
var portMngFileTransfer = 38250; // file transfer port number of Coconut Manager
var portMngInternalHttp = 38280; // http port number of Coconut Manager for Coconut Agent
var portMngExternalHttp = 38290; // http port number of Coconut Manager for Tool User

var portAgentRpc = 38390;
var portAgentFileTransfer = 38380;

**Comment by blackwitch** [comment]
var portMngInternalHttp = 38280; // http port number of Coconut Manager for Coconut Agent
var portMngExternalHttp = 38290; // http port number of Coconut Manager for Tool User

위 두가지는 http를 활용하기 때문에 가능하면 기본 포트와 유사하게 설정하는게 더 쉽게 이해할 수 있을 듯 합니다. 

그래서 저의 의견은 아래와 같습니다.

var portMngInternalHttp = 38080; // http port number of Coconut Manager for Coconut Agent
var portMngExternalHttp = 38443; // http port number of Coconut Manager for Tool User
     (portMngExternalHttp는 추후 https로 완전히 수정될 예정입니다.)

의견 부탁드리며, 건의 주셨던 포트나 제가 의견을 드린 포트나 사실 아주 큰 차이는 없다고 생각됩니다. 그래서 흥배님이 보시고 결정 후 업데이트를 부탁드립니다. 

각 건의를 실제 코드에 반영할 때는  의견을 주셨던 분들의 작업으로 기록에 남았으면 합니다. 

해당 내용을 직접 수정해서 올려주시면 master에 업데이트 하겠습니다. 

혹시 여건상 작업하기 어렵다고 하시면 제가 업데이트 하겠습니다. ^^

**Comment by jacking75** [comment]
네 그럼 지현님 의견을 반영해서 제가 수정 후 pull request 보내겠습니다^^

**Comment by blackwitch** [comment]
master에 적용했습니다. 문서는 좀 더 다듬어야 할 듯 합니다. 저도 시간내서 수정해 보겠습니다. 

수고하셨습니다. ^^
