### ISSUE TITLE
서비스 고유의 기능 구현에 대한 가이드 라인이 필요합니다

### ISSUE THREAD

**Issue by jacking75** [blackwitch/Coconut#8]
Coconut을 각 게임 서비스에서 사용할 때 해당 서비스에서 필요로 하는 기능을 Coconut에 구현해야 할 때 어떤 식으로 하면 좋을지에 대한 가이드라인이 있었으면 좋겠습니다.

예를들어 제가 만든 게임은 서비스할 때 '5분 단위로 동시접속자 수 저장' 이라는 기능이 필요한데 이 기능은 Agent에서 5분 단위로 각 게임서버에 동시접속자수로 요청해서, 답변을 받은 후 Agent가 특정 DB에 저장합니다.

위 기능을 구현하기 위해서 Sensu 라는 오픈소스 프레임워크처럼 '플러그인' 기능을 제공해서 제가 여기에 구현하면 될지, 혹은 기존의 Coconut에 어떤 식으로 추가하면 좋은지 가이드라인을 잡아주었으면 좋겠습니다.
제가 만든 게임만을 위한 기능이 최대한 기존의 Coconut에 영향을 미치지 않으면서 구현할 수 있으면 좋겠습니다(이렇게 되야 Coconut가 변경이 있어서 업데이트를 해도 제가 만든 코드에 영향이 없겠죠)

**Comment by blackwitch** [comment]
이전에 논의했던 플러그인 방식으로 구현하면 되지 않을까 생각됩니다. 상세한 내용에 대해서는 금주 중에 1차 정리해서 공유해 드리겠습니다. 좋은 밤 되세요. ^^

**Comment by blackwitch** [comment]
관련해서 Coconut의 향후 일정을 수정했습니다.

건의 하신 내용은 이전에 논의했던 스케쥴러의 논의와 유사하여 해당 이슈를 6월까지 개발을 완료하는 목표로 수정하였습니다. 

Coconut에 플러그인 메니져를 두고, 가동시 제작된 플러그인을 로딩하여 활용하는 방법으로 디자인을 할 예정입니다. 

금주 중에 초안 제작을 진행해 보겠습니다. 

해당 이슈는 디자인이 완전히 확정될 때까지 유지하겠습니다. 

의견 감사합니다. :)

**Comment by jacking75** [comment]
고맙습니다^^

**Comment by blackwitch** [comment]
주말동안 여러가지를 고민 중, js-plugins 을 사용하여 플러그인 시스템을 구현해보고 있습니다. 

https://www.npmjs.com/package/js-plugins

참고하셔서 다른 의견 있으시면 건의 부탁드립니다.

즐거운 한 주 되세요. ^^

**Comment by jacking75** [comment]
괜찮을 것 같네요^^

**Comment by blackwitch** [comment]
https://www.npmjs.com/package/architect 

이걸로 변경했습니다. 샘플까지 제작했는데 문제 없을 듯 합니다.

**Comment by blackwitch** [comment]
플러그인 시스템을 추가했으며, 샘플로 pushbullet 을 활용한 alarm을 추가했습니다. 

검토해 보시고 문제 없다고 판단되시면 이슈를 닫아주세요. :)

**Comment by blackwitch** [comment]
특별히 의견이 없으신 듯 해서 이슈는 닫겠습니다. 추가 내용이 있다면 별도 이슈로 올려주세요.
