### ISSUE TITLE
개발 진행 공유

### ISSUE THREAD

**Issue by jacking75** [blackwitch/Coconut#9]
Coconut 작업 중 현재 하고 있는 것과 앞으로 할 일을 트렐로(https://www.trello.com/)로 공유하면 좋을 것 같습니다.
Coconut의 현재 상태를 쉽게 알 수 있거, 버그나 요청을 하기 전에 중복을 막을 수 있을 것 같습니다^^

**Comment by blackwitch** [comment]
manual goal 을 보시면 현재 진행 사항을 텍스트로 남기고 있습니다. 
상세 개발 버전은 요청하신대로 trello에 생성했습니다. jacking75로 검색했는데 inactive user라고 되어 있는데 확인 부탁드립니다.

**Comment by blackwitch** [comment]
처리 완료되어 해당 이슈를 닫겠습니다.
